import express from "express";
import {topSongs} from "../functions/topSongs";
import { search } from "../functions/search";
import { login } from "../functions/login";
import { addToQueue } from "../functions/addToQueue";
const router=express.Router();
router.get("/topSongs",topSongs);
router.get("/search",search);
router.post("/login",login);
router.post("/addToQueue",addToQueue);
export default router;